Vagrant.configure("2") do |config|
  config.vm.define :base do |base|
    base.vm.box = "centos/5"
    base.vm.provider :libvirt do |domain|
      domain.memory = 1024
      domain.cpus = 1
    end
  end
end

